"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.PROPERTY_OFFER_DESCRIPTION = exports.SPECIAL_LINK = exports.PROPERTY_OFFER_IMAGE = exports.ASSOCIATE_IMAGE = exports.CITY_FEATURED_IMAGE = exports.PROPERTY_LOCATION_REGION = exports.PROPERTY_LOCATION_CITY = exports.HOME_PAGE = exports.WEBSITE_HOME_PAGE_FEATURED_IMAGE = exports.APP_HOME_PAGE_FEATURED_IMAGE = exports.CUSTOMER_TYPE = exports.BANK_PROPERTY = exports.LINKED_PROPERTY = exports.NEWS = exports.CUSTOMER = exports.PROPERTY_OTHER_IMAGE = exports.PROPERTY_VIDEO = exports.PROPERTY_LINK = exports.PROPERTY_PHOTO = exports.PROPERTY_PDF = exports.PROPERTY_OFFER_CUSTOMER_TYPE = exports.PROPERTY_OFFER = exports.PROPERTY_BUY_OPTION = exports.PROPERTY = exports.BANK = exports.BUILDER = exports.SUB_ADMIN = exports.ADMIN = void 0;
const mongoose_1 = __importDefault(require("mongoose"));
const dotenv_1 = __importDefault(require("dotenv"));
dotenv_1.default.config();
const connectionString = String(process.env.MONGODB_URL);
mongoose_1.default.connect(connectionString).then(() => { console.log("connected to MongoDB"); }).catch((err) => { console.log("Unable to connect to MongoDB" + err); });
const admin_model_1 = require("../models/admin.model");
const subadmin_model_1 = require("../models/subadmin.model");
const builder_model_1 = require("../models/builder.model");
const property_model_1 = require("../models/property.model");
const property_buy_option_model_1 = require("../models/property.buy.option.model");
const property_offer_model_1 = require("../models/property.offer.model");
const property_pdf_model_1 = require("../models/property.pdf.model");
const property_photo_model_1 = require("../models/property.photo.model");
const property_link_model_1 = require("../models/property.link.model");
const property_video_model_1 = require("../models/property.video.model");
const property_other_image_model_1 = require("../models/property.other.image.model");
const customer_model_1 = require("../models/customer.model");
const news_model_1 = require("../models/news.model");
const liked_property_model_1 = require("../models/liked.property.model");
const bank_model_1 = require("../models/bank.model");
const bank_property_model_1 = require("../models/bank.property.model");
const customer_type_model_1 = require("../models/customer.type.model");
const apphomepagefeaturedimage_model_1 = require("../models/apphomepagefeaturedimage.model");
const websiteHomePageFeaturedImage_model_1 = require("../models/websiteHomePageFeaturedImage.model");
const homepage_model_1 = require("../models/homepage.model");
const propertyLocationCity_model_1 = require("../models/propertyLocationCity.model");
const propertyLocationRegion_model_1 = require("../models/propertyLocationRegion.model");
const cityFeaturedImages_model_1 = require("../models/cityFeaturedImages.model");
const associateImage_model_1 = require("../models/associateImage.model");
const property_offer_customer_type_model_1 = require("../models/property.offer.customer.type.model");
const property_offer_image_model_1 = require("../models/property.offer.image.model");
const special_link_model_1 = require("../models/special.link.model");
const property_offer_description_model_1 = require("../models/property.offer.description.model");
exports.ADMIN = mongoose_1.default.model("admin", admin_model_1.adminSchema);
exports.SUB_ADMIN = mongoose_1.default.model("subadmin", subadmin_model_1.subAdminSchema);
exports.BUILDER = mongoose_1.default.model("builder", builder_model_1.builderSchema);
exports.BANK = mongoose_1.default.model("bankOffer", bank_model_1.bankSchema);
exports.PROPERTY = mongoose_1.default.model("property", property_model_1.propertySchema);
exports.PROPERTY_BUY_OPTION = mongoose_1.default.model("propertyBuyOption", property_buy_option_model_1.propertyBuyOptionSchema);
exports.PROPERTY_OFFER = mongoose_1.default.model('propertyOffer', property_offer_model_1.propertyOfferSchema);
exports.PROPERTY_OFFER_CUSTOMER_TYPE = mongoose_1.default.model('propertyOfferCustomerType', property_offer_customer_type_model_1.propertyOfferCustomerTypeSchema);
exports.PROPERTY_PDF = mongoose_1.default.model('propertyPDF', property_pdf_model_1.propertyPDFSchema);
exports.PROPERTY_PHOTO = mongoose_1.default.model('propertyPhoto', property_photo_model_1.propertyPhotoSchema);
exports.PROPERTY_LINK = mongoose_1.default.model('propertyLink', property_link_model_1.propertyLinkSchema);
exports.PROPERTY_VIDEO = mongoose_1.default.model('propertyVideo', property_video_model_1.propertyVideoSchema);
exports.PROPERTY_OTHER_IMAGE = mongoose_1.default.model('propertyOtherImage', property_other_image_model_1.propertyOtherImageSchema);
exports.CUSTOMER = mongoose_1.default.model('customer', customer_model_1.customerSchema);
exports.NEWS = mongoose_1.default.model('news', news_model_1.newsSchema);
exports.LINKED_PROPERTY = mongoose_1.default.model('linkedProperty', liked_property_model_1.likedPropertySchema);
exports.BANK_PROPERTY = mongoose_1.default.model('bankProperty', bank_property_model_1.bankPropertySchema);
exports.CUSTOMER_TYPE = mongoose_1.default.model('customerType', customer_type_model_1.customerTypeSchema);
exports.APP_HOME_PAGE_FEATURED_IMAGE = mongoose_1.default.model('appHomePageFeaturedImage', apphomepagefeaturedimage_model_1.appHomePageFeaturedImageSchema);
exports.WEBSITE_HOME_PAGE_FEATURED_IMAGE = mongoose_1.default.model('websiteHomePageFeaturedImage', websiteHomePageFeaturedImage_model_1.websiteHomePageFeaturedImageSchema);
exports.HOME_PAGE = mongoose_1.default.model('homepage', homepage_model_1.homepagesSchema);
exports.PROPERTY_LOCATION_CITY = mongoose_1.default.model("propertyLocationCities", propertyLocationCity_model_1.propertyLocationCitySchema);
exports.PROPERTY_LOCATION_REGION = mongoose_1.default.model("propertyLocationRegions", propertyLocationRegion_model_1.propertyLocationRegionSchema);
exports.CITY_FEATURED_IMAGE = mongoose_1.default.model("cityFeaturedImage", cityFeaturedImages_model_1.cityFeaturedImagesSchema);
exports.ASSOCIATE_IMAGE = mongoose_1.default.model("associateImage", associateImage_model_1.associateImageSchema);
exports.PROPERTY_OFFER_IMAGE = mongoose_1.default.model('propertyOfferImage', property_offer_image_model_1.propertyOfferImageSchema);
exports.SPECIAL_LINK = mongoose_1.default.model('specialLink', special_link_model_1.specialLinkSchema);
exports.PROPERTY_OFFER_DESCRIPTION = mongoose_1.default.model('propertyOfferDescription', property_offer_description_model_1.propertyOfferDescriptionSchema);
//# sourceMappingURL=mongodb.js.map