"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.adminRouter = void 0;
const express_1 = require("express");
const token_middleware_1 = require("../middlewares/token.middleware");
const admin_create_controller_1 = require("../controllers/admin/admin.create.controller");
const admin_login_phone_and_password_controller_1 = require("../controllers/admin/admin.login.phone.and.password.controller");
const admin_logout_controller_1 = require("../controllers/admin/admin.logout.controller");
const admin_get_list_controller_1 = require("../controllers/admin/admin.get.list.controller");
const admin_get_info_controller_1 = require("../controllers/admin/admin.get.info.controller");
const admin_check_email_controller_1 = require("../controllers/admin/admin.check.email.controller");
const admin_search_by_name_controller_1 = require("../controllers/admin/admin.search.by.name.controller");
const admin_update_profilePicture_controller_1 = require("../controllers/admin/admin.update.profilePicture.controller");
const admin_update_controller_1 = require("../controllers/admin/admin.update.controller");
const admin_delete_controller_1 = require("../controllers/admin/admin.delete.controller");
const admin_delete_subAdmin_controller_1 = require("../controllers/admin/admin.delete.subAdmin.controller");
exports.adminRouter = (0, express_1.Router)({ caseSensitive: true, strict: true });
exports.adminRouter.post("/create", token_middleware_1.getAccessTokenInfo, admin_create_controller_1.adminCreateController);
exports.adminRouter.post("/login/phoneAndPassword", admin_login_phone_and_password_controller_1.adminLoginPhoneAndPasswordController);
exports.adminRouter.delete("/logout", token_middleware_1.getAccessTokenInfo, admin_logout_controller_1.adminLogoutController);
exports.adminRouter.get("/get/list", token_middleware_1.getAccessTokenInfo, admin_get_list_controller_1.adminGetListController);
exports.adminRouter.get("/get/info", token_middleware_1.getAccessTokenInfo, admin_get_info_controller_1.adminGetInfoController);
exports.adminRouter.get("/get/isEmailPresent", token_middleware_1.getAccessTokenInfo, admin_check_email_controller_1.adminCheckEmailController);
exports.adminRouter.get("/search/name", token_middleware_1.getAccessTokenInfo, admin_search_by_name_controller_1.adminSearchByNameController);
exports.adminRouter.put("/update/profilePicture", token_middleware_1.getAccessTokenInfo, admin_update_profilePicture_controller_1.adminUpdateProfilePictureController);
exports.adminRouter.put("/update", token_middleware_1.getAccessTokenInfo, admin_update_controller_1.adminUpdateController);
exports.adminRouter.delete("/delete", token_middleware_1.getAccessTokenInfo, admin_delete_controller_1.adminDeleteController);
exports.adminRouter.delete("/delete/subAdmin", token_middleware_1.getAccessTokenInfo, admin_delete_subAdmin_controller_1.adminDeleteSubAdminController);
//# sourceMappingURL=admin.routes.js.map