"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.builderRouter = void 0;
const express_1 = require("express");
const token_middleware_1 = require("../middlewares/token.middleware");
const multer_middleware_1 = require("../middlewares/multer.middleware");
const builder_create_controller_1 = require("../controllers/builder/builder.create.controller");
const builder_delete_controller_1 = require("../controllers/builder/builder.delete.controller");
const builder_get_controller_1 = require("../controllers/builder/builder.get.controller");
const builder_update_controller_1 = require("../controllers/builder/builder.update.controller");
const builder_update_logo_controller_1 = require("../controllers/builder/builder.update.logo.controller");
const builder_get_list_controller_1 = require("../controllers/builder/builder.get.list.controller");
const builder_get_count_controller_1 = require("../controllers/builder/builder.get.count.controller");
const getBuilderPropertyCount_controller_1 = require("../controllers/builder/getBuilderPropertyCount.controller");
const getBuilderActivePropertyCount_controller_1 = require("../controllers/builder/getBuilderActivePropertyCount.controller");
const getBuilderListingPropertyCount_controller_1 = require("../controllers/builder/getBuilderListingPropertyCount.controller");
const getListingCount_controller_1 = require("../controllers/builder/getListingCount.controller");
const getPropertiesList_controller_1 = require("../controllers/builder/getPropertiesList.controller");
const getCompressedPropertiesList_controller_1 = require("../controllers/builder/getCompressedPropertiesList.controller");
const searchBuildersByName_controller_1 = require("../controllers/builder/searchBuildersByName.controller");
const updateBuilderActiveStatus_controller_1 = require("../controllers/builder/updateBuilderActiveStatus.controller");
const builder_update_coverImage_controller_1 = require("../controllers/builder/builder.update.coverImage.controller");
exports.builderRouter = (0, express_1.Router)({ caseSensitive: true, strict: true });
exports.builderRouter.post('/create', token_middleware_1.getAccessTokenInfo, multer_middleware_1.Multer.single('logo'), builder_create_controller_1.builderCreateController);
exports.builderRouter.delete('/delete', token_middleware_1.getAccessTokenInfo, builder_delete_controller_1.builderDeleteController);
exports.builderRouter.get('/get', builder_get_controller_1.builderGetController);
exports.builderRouter.get('/get/list', builder_get_list_controller_1.builderGetListController);
exports.builderRouter.patch('/update', token_middleware_1.getAccessTokenInfo, builder_update_controller_1.builderUpdateController);
exports.builderRouter.patch('/update/logo', token_middleware_1.getAccessTokenInfo, multer_middleware_1.Multer.single('logo'), builder_update_logo_controller_1.builderUpdateLogoController);
exports.builderRouter.patch('/update/coverImage', token_middleware_1.getAccessTokenInfo, multer_middleware_1.Multer.single('coverImage'), builder_update_coverImage_controller_1.builderUpdateCoverImageController);
exports.builderRouter.get("/get/count", builder_get_count_controller_1.getBuilderCount);
exports.builderRouter.get("/get/builderPropertyCount", getBuilderPropertyCount_controller_1.getBuilderPropertyCount);
exports.builderRouter.get("/get/builderActivePropertyCount", getBuilderActivePropertyCount_controller_1.getBuilderActivePropertyCount);
exports.builderRouter.get("/get/builderListingPropertyCount", getBuilderListingPropertyCount_controller_1.getBuilderListingPropertyCount);
exports.builderRouter.get("/get/listingCount", getListingCount_controller_1.getListingCount);
exports.builderRouter.get("/get/propertiesList", getPropertiesList_controller_1.getPropertiesList);
exports.builderRouter.get("/get/propertiesList/compressed", getCompressedPropertiesList_controller_1.getCompressedPropertiesList);
exports.builderRouter.get("/search/name", searchBuildersByName_controller_1.searchBuildersByName);
exports.builderRouter.put("/update/activeStatus", token_middleware_1.getAccessTokenInfo, updateBuilderActiveStatus_controller_1.updateBuilderActiveStatus);
//# sourceMappingURL=builder.routes.js.map