"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.propertyRouter = void 0;
const express_1 = require("express");
const token_middleware_1 = require("../middlewares/token.middleware");
const multer_middleware_1 = require("../middlewares/multer.middleware");
const property_create_controller_1 = require("../controllers/property/property.create.controller");
const property_delete_controller_1 = require("../controllers/property/property.delete.controller");
const property_get_controller_1 = require("../controllers/property/property.get.controller");
const property_get_list_controller_1 = require("../controllers/property/property.get.list.controller");
const property_update_controller_1 = require("../controllers/property/property.update.controller");
const property_get_count_controller_1 = require("../controllers/property/property.get.count.controller");
const property_get_activeCount_controller_1 = require("../controllers/property/property.get.activeCount.controller");
const property_get_listingCount_controller_1 = require("../controllers/property/property.get.listingCount.controller");
const property_get_propertyByLatitudeAndLongitude_controller_1 = require("../controllers/property/property.get.propertyByLatitudeAndLongitude.controller");
const property_get_propertyCountForLatAndLong_controller_1 = require("../controllers/property/property.get.propertyCountForLatAndLong.controller");
const property_search_address_controller_1 = require("../controllers/property/property.search.address.controller");
const property_search_city_controller_1 = require("../controllers/property/property.search.city.controller");
const property_search_reraID_controller_1 = require("../controllers/property/property.search.reraID.controller");
const property_update_coverImage_controller_1 = require("../controllers/property/property.update.coverImage.controller");
const property_get_propertyListByMultipleFilter_controller_1 = require("../controllers/property/property.get.propertyListByMultipleFilter.controller");
const property_get_propertyLocalityAndBuilderByCityAndSearch_controller_1 = require("../controllers/property/property.get.propertyLocalityAndBuilderByCityAndSearch.controller");
const property_search_region_controller_1 = require("../controllers/property/property.search.region.controller");
const property_search_cityAndRegion_controller_1 = require("../controllers/property/property.search.cityAndRegion.controller");
const property_get_propertyTypeList_controller_1 = require("../controllers/property/property.get.propertyTypeList.controller");
const property_search_name_controller_1 = require("../controllers/property/property.search.name.controller");
const property_get_propertyByFilterCompressed_controller_1 = require("../controllers/property/property.get.propertyByFilterCompressed.controller");
const property_get_propertyByFilter_controller_1 = require("../controllers/property/property.get.propertyByFilter.controller");
exports.propertyRouter = (0, express_1.Router)({ caseSensitive: true, strict: true });
exports.propertyRouter.post("/create", token_middleware_1.getAccessTokenInfo, multer_middleware_1.Multer.single("coverImage"), property_create_controller_1.propertyCreateController);
exports.propertyRouter.get("/get", property_get_controller_1.propertyGetController);
exports.propertyRouter.get("/get/count", property_get_count_controller_1.propertyGetCountController);
exports.propertyRouter.get("/get/activeCount", property_get_activeCount_controller_1.propertyGetActiveCountController);
exports.propertyRouter.get("/get/listingCount", property_get_listingCount_controller_1.propertyGetListingCountController);
exports.propertyRouter.get("/get/list", property_get_list_controller_1.propertyGetListController);
exports.propertyRouter.get("/get/propertyByLatitudeAndLongitude", property_get_propertyByLatitudeAndLongitude_controller_1.propertyGetByLatLngController);
exports.propertyRouter.get("/get/propertyCountForLatAndLong", property_get_propertyCountForLatAndLong_controller_1.propertyCountForLatAndLongController);
exports.propertyRouter.get("/search/address", property_search_address_controller_1.propertySearchByAddressController);
exports.propertyRouter.get("/search/city", property_search_city_controller_1.propertySearchByCityController);
exports.propertyRouter.get("/search/reraID", property_search_reraID_controller_1.propertySearchByReraIDController);
exports.propertyRouter.get("/search/name", property_search_name_controller_1.propertySearchByNameController);
exports.propertyRouter.get("/search/region", property_search_region_controller_1.propertySearchByRegionController);
exports.propertyRouter.get("/search/cityAndRegion", property_search_cityAndRegion_controller_1.propertySearchByCityAndRegionController);
exports.propertyRouter.get("/get/propertyByFilter", property_get_propertyByFilter_controller_1.propertyGetByFilterController);
exports.propertyRouter.get("/get/propertyByFilterCompressed", property_get_propertyByFilterCompressed_controller_1.propertyGetByFilterCompressedController);
exports.propertyRouter.get("/get/propertyListByMultipleFilter", property_get_propertyListByMultipleFilter_controller_1.propertyGetListByMultipleFilterController);
exports.propertyRouter.get("/get/propertyLocalityAndBuilderByCityAndSearch", property_get_propertyLocalityAndBuilderByCityAndSearch_controller_1.propertyGetLocalityAndBuilderController);
exports.propertyRouter.get("/get/propertyTypeList", property_get_propertyTypeList_controller_1.propertyGetTypeListController);
exports.propertyRouter.patch("/update", token_middleware_1.getAccessTokenInfo, property_update_controller_1.propertyUpdateController);
exports.propertyRouter.patch("/update/coverImage", token_middleware_1.getAccessTokenInfo, multer_middleware_1.Multer.single("coverImage"), property_update_coverImage_controller_1.propertyUpdateCoverImageController);
exports.propertyRouter.delete("/delete", token_middleware_1.getAccessTokenInfo, property_delete_controller_1.propertyDeleteController);
//# sourceMappingURL=property.routes.js.map