"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.propertyLocationRouter = void 0;
const express_1 = require("express");
const token_middleware_1 = require("../middlewares/token.middleware");
const propertyLocation_city_create_controller_1 = require("../controllers/propertyLocation/propertyLocation.city.create.controller");
const propertyLocation_city_get_controller_1 = require("../controllers/propertyLocation/propertyLocation.city.get.controller");
const propertyLocation_city_getList_controller_1 = require("../controllers/propertyLocation/propertyLocation.city.getList.controller");
const propertyLocation_city_search_controller_1 = require("../controllers/propertyLocation/propertyLocation.city.search.controller");
const propertyLocation_city_update_controller_1 = require("../controllers/propertyLocation/propertyLocation.city.update.controller");
const propertyLocation_city_delete_controller_1 = require("../controllers/propertyLocation/propertyLocation.city.delete.controller");
const propertyLocation_region_create_controller_1 = require("../controllers/propertyLocation/propertyLocation.region.create.controller");
const propertyLocation_region_get_controller_1 = require("../controllers/propertyLocation/propertyLocation.region.get.controller");
const propertyLocation_region_getList_controller_1 = require("../controllers/propertyLocation/propertyLocation.region.getList.controller");
const propertyLocation_region_search_controller_1 = require("../controllers/propertyLocation/propertyLocation.region.search.controller");
const propertyLocation_region_update_controller_1 = require("../controllers/propertyLocation/propertyLocation.region.update.controller");
const propertyLocation_region_delete_controller_1 = require("../controllers/propertyLocation/propertyLocation.region.delete.controller");
exports.propertyLocationRouter = (0, express_1.Router)({ caseSensitive: true, strict: true });
exports.propertyLocationRouter.post("/city/create", token_middleware_1.getAccessTokenInfo, propertyLocation_city_create_controller_1.createCityController);
exports.propertyLocationRouter.get("/city/get", propertyLocation_city_get_controller_1.getCityController);
exports.propertyLocationRouter.get("/city/getList", propertyLocation_city_getList_controller_1.getCityListController);
exports.propertyLocationRouter.get("/city/search", propertyLocation_city_search_controller_1.searchCityController);
exports.propertyLocationRouter.patch("/city/update", token_middleware_1.getAccessTokenInfo, propertyLocation_city_update_controller_1.updateCityController);
exports.propertyLocationRouter.delete("/city/delete", token_middleware_1.getAccessTokenInfo, propertyLocation_city_delete_controller_1.deleteCityController);
exports.propertyLocationRouter.post("/region/create", token_middleware_1.getAccessTokenInfo, propertyLocation_region_create_controller_1.createRegionController);
exports.propertyLocationRouter.get("/region/get", propertyLocation_region_get_controller_1.getRegionController);
exports.propertyLocationRouter.get("/region/getList", propertyLocation_region_getList_controller_1.getRegionListController);
exports.propertyLocationRouter.get("/region/search", propertyLocation_region_search_controller_1.searchRegionController);
exports.propertyLocationRouter.patch("/region/update", token_middleware_1.getAccessTokenInfo, propertyLocation_region_update_controller_1.updateRegionController);
exports.propertyLocationRouter.delete("/region/delete", token_middleware_1.getAccessTokenInfo, propertyLocation_region_delete_controller_1.deleteRegionController);
//# sourceMappingURL=propertyLocation.routes.js.map